apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: fhirmessage
  name: fhirmessage
  namespace: default
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 9999
  selector:
    app: fhirmessage
  type: LoadBalancer
status:
  loadBalancer: {}